### ISSUE TITLE
Support v5.8.1

### ISSUE THREAD

**Issue by craftzdog** [0NotApplicable0/inkdrop-nord-preview-theme#4]
## Incorrect codeblock text color

As of [v5.8.1](https://forum.inkdrop.app/t/inkdrop-desktop-v5-8-1-beta-1/4564), it embeds the default preview styles.
But it causes the codeblock text color to be incorrect in Nord.

![image](https://github.com/0NotApplicable0/inkdrop-nord-preview-theme/assets/1332805/fa27c200-539a-4b04-a641-39e1b708cecf)

This is because the name of the Nord UI doesn't end with `-dark-ui`, so it assumes the color scheme is light.
To avoid that, you have to specify the correct text color in the preview theme.

## Remove styles for GFM alerts and metadata section

`gfm-alerts.css` or `metadata-section.css` is no longer necessary as of v5.8.1.

Would you fix it?

You can target the engine to

```
  "engines": {
    "inkdrop": "^5.8.1"
  },
```

**Comment by 0NotApplicable0** [comment]
Hey @craftzdog working on these changes in a feature branch v5.8.1_support and will get that merged in!

**Comment by 0NotApplicable0** [comment]
Fixed in inkdrop-nord-syntax-theme v1.7.0 however v1.3.0 of inkdrop-nord-preview-theme removes those unneeded css files.
Thank you!
